services:
  otel-collector:
    container_name: otel-collector

  rabbitmq:
    container_name: rabbitmq

  jaeger:
    container_name: jaeger

  loki:
    container_name: loki

  prometheus:
    container_name: prometheus

  grafana:
    container_name: grafana

  powrintegration-backoffice:
    container_name: powrintegration_backoffice
    image: powrintegration-backoffice:dev
    build:
      context: .
      dockerfile: ./PowrIntegration.BackOfficeService/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      otel-collector:
        condition: service_started
    environment:
      DOTNET_ENVIRONMENT: Development

  powrintegration-zra:
    container_name: powrintegration_zra
    image: powrintegration-zra:dev
    build:
      context: .
      dockerfile: ./PowrIntegration.ZraService/Dockerfile
      args:
        - BUILD_CONFIGURATION=Debug
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
      otel-collector:
        condition: service_started
    environment:
      DOTNET_ENVIRONMENT: Development
      ZraApi__BaseUrl: http://host.docker.internal:8080/sandboxvdsc/