services:
    otel-collector:
        deploy:
            mode: global

    prometheus:
        deploy:
            mode: global

    loki:
        deploy:
            mode: global

    jaeger:
        deploy:
            mode: global

    grafana:
        deploy:
            mode: global

    rabbitmq:
        deploy:
            mode: global

    powrintegration-backoffice:
        image: cjsunnysa/powrintegration-backoffice:release-latest
        deploy:
            mode: replicated
            replicas: 1

    powrintegration-zra:
        image: cjsunnysa/powrintegration-zra:release-latest
        deploy:
            mode: replicated
            replicas: 1

