services:
  otel-collector:
    image: otel/opentelemetry-collector:0.120.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./container-files/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    depends_on:
      - jaeger
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:v3.1.0
    volumes:
      - ./container-files/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  loki:
    image: grafana/loki:3.3.2
    user: root
    volumes:
      - ./container-files/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  jaeger:
    image: jaegertracing/all-in-one:1.65.0
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    volumes:
      - jaeger_data:/tmp
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
      - "14250:14250"  # OTLP gRPC

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./container-files/loki-datasource.yaml:/etc/grafana/provisioning/datasources/loki.yaml
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=false
      - GF_SMTP_HOST=smtp.mail.yahoo.com:587
      - GF_SMTP_FROM_ADDRESS=powerpos_alers@yahoo.com
      - GF_SMTP_FROM_NAME="Power POS Alerts"
    depends_on:
      - prometheus
      - loki
      - jaeger
  
  rabbitmq:
    image: rabbitmq:4.0.5-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672" # RabbitMQ main port
      - "15672:15672" # Management console
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  powrintegration-backoffice:
    environment:
      DOTNET_ENVIRONMENT: Release
      Service__TimeoutSeconds: 10
      ZraApi__TaxMappings: |
        '[
            { "SalesGroupId": 44, "TaxGroupId": 2, "TaxTypeCode": "D" }, 
            { "SalesGroupId": 62, "TaxGroupId": 2, "TaxTypeCode": "D" }
        ]'
    volumes:
      - C:\\PowerTill8:/export
      - C:\\PowrIntegration:/usr/local/powrintegration

  powrintegration-zra:
    environment:
      DOTNET_ENVIRONMENT: Release
      Service__TimeoutSeconds: 10
      ZraApi__BaseUrl: http://0.0.0.0:8080/sandboxvdsc/
      ZraApi__TaxMappings: |
        '[
            { "SalesGroupId": 44, "TaxGroupId": 2, "TaxTypeCode": "D" }, 
            { "SalesGroupId": 62, "TaxGroupId": 2, "TaxTypeCode": "D" }
        ]'

volumes:
  rabbitmq_data:
  grafana_data:
  prometheus_data:
  loki_data:
  jaeger_data:  