services:
    otel-collector:
        deploy:
            mode: global
        ports:
            - "4317:4317"  # OTLP gRPC
            - "4318:4318"  # OTLP HTTP

    prometheus:
        deploy:
            mode: global
        ports:
            - "9090:9090"

    loki:
        deploy:
            mode: global
        ports:
            - "3100:3100"

    jaeger:
        deploy:
            mode: global
        ports:
            - "16686:16686"  # Jaeger UI
            - "14268:14268"  # Jaeger collector
            - "14250:14250"  # OTLP gRPC

    grafana:
        deploy:
            mode: global
        ports:
            - "3000:3000"

    rabbitmq:
        deploy:
            mode: global
        ports:
            - "5672:5672"   # RabbitMQ main port
            - "15672:15672" # Management console

    powrintegration-backoffice:
        image: cjsunnysa/powrintegration-backoffice:release-latest
        depends_on: [otel-collector, rabbitmq]
        deploy:
            mode: replicated
            replicas: 1

    powrintegration-zra:
        image: cjsunnysa/powrintegration-zra:release-latest
        depends_on: [otel-collector, rabbitmq]
        deploy:
            mode: replicated
            replicas: 1

