name: 'Build and Push to DockerHub'
description: 'Builds a service with a tag and pushes the image to DockerHub'
inputs:
  username: 
    description: 'The secret username for DockerHub login'
    required: true
  password:
    description: 'The secret password for DockerHub login'
    required true
  serviceName:
    description: 'The name of the service for display'
    required: true
  dockerfile:
    description: 'The dockerfile to use to build the image'
    required: true
  tag:
    description: 'The repostiory name'
    required: true
  version:
    description: 'The version tag of the image'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to Docker Hub
      run: echo '${{ inputs.password }}' | docker login -u "${{ inputs.username }}" --password-stdin

    - name: Build and Push ${{ inputs.serviceName }} Image
      run: |
        docker build -t ${{ inputs.tag }}:${{ inputs.version }} -f ${{ inputs.dockerfile }} .
        docker push ${{ inputs.tag }}:${{ inputs.version }}