name: 'Build and Push to DockerHub'
description: 'Builds a service with a tag and pushes the image to DockerHub'
inputs:
  serviceName:
    description: 'The name of the service for display'
    required: true
  dockerfile:
    description: 'The dockerfile to use to build the image'
    required: true
  tag:
    description: 'The repostiory name'
    required: true
  version:
    description: 'The version tag of the image'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Log in to Docker Hub
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push ${{ serviceName }} Image
      run: |
        docker build -t ${{ tag }}:${{ version }} -f ${{ dockerfile }} .
        docker push ${{ tag }}:${{ version }}