name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: "BackOffice"
            dockerfile: "PowrIntegration.BackOfficeService/Dockerfile"
            tag: "cjsunnysa/powrintegration-backoffice"
          - name: "Zra"
            dockerfile: "PowrIntegration.ZraService/Dockerfile"
            tag: "cjsunnysa/powrintegration-zra"
        version:
          - ${{ github.sha }}
          - 'latest'

    steps:
      - uses: 'actions/build-and-publish'
        with:
          serviceName: ${{ matrix.service.name }}
          dockerfile: ${{ matrix.service.dockerfile }}
          tag: ${{ matrix.service.tag }}
          version: ${{ matrix.version }}
