name: Build and Push Docker Dev Image

on:
  push:
    branches:
      - dev
  pull_request: 
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: "BackOffice"
            dockerfile: "PowrIntegration.BackOfficeService/Dockerfile"
            tag: "cjsunnysa/powrintegration-backoffice"
          - name: "Zra"
            dockerfile: "PowrIntegration.ZraService/Dockerfile"
            tag: "cjsunnysa/powrintegration-zra"
        version:
          - 'dev'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/build-and-publish
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          serviceName: ${{ matrix.service.name }}
          dockerfile: ${{ matrix.service.dockerfile }}
          tag: ${{ matrix.service.tag }}
          version: ${{ matrix.version }}
