name: Build and Push Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        service:
          - name: "BackOffice"
            dockerfile: "PowrIntegration.BackOfficeService/Dockerfile"
            tag: "cjsunnysa/powrintegration-backoffice"
          - name: "Zra"
            dockerfile: "PowrIntegration.ZraService/Dockerfile"
            tag: "cjsunnysa/powrintegration-zra"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push ${{ matrix.service.name }} Image
        run: |
          docker build -t ${{ matrix.service.tag }}:${{ github.sha }} -f ${{ matrix.service.dockerfile }} .
          docker push ${{ matrix.service.tag }}:${{ github.sha }}
